# Generated by Django 5.2.4 on 2025-08-06 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the %(class)s was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the %(class)s was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="The lead's first name (max 100 characters)",
                        max_length=100,
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="The lead's last name (max 100 characters)",
                        max_length=100,
                        verbose_name="Last name",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="The lead's middle name (optional, max 100 characters)",
                        max_length=100,
                        null=True,
                        verbose_name="Middle name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Contact phone number (max 20 characters)",
                        max_length=20,
                        unique=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Valid email address",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related advertisement campaign (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="advertisements.advertisement",
                        verbose_name="Advertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="lead_name_idx"
                    ),
                    models.Index(fields=["email"], name="lead_email_idx"),
                    models.Index(fields=["created_at"], name="lead_created_at_idx"),
                ],
            },
        ),
    ]
