# Generated by Django 5.2.4 on 2025-08-08 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the %(class)s was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the %(class)s was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official contract reference number/name",
                        max_length=255,
                        verbose_name="Contract name",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Scanned contract file (PDF or Word)",
                        upload_to="contracts/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="Document",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Service start date", verbose_name="Start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Service end date", verbose_name="End date"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total contract value",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-cost"],
            },
        ),
    ]
