# Generated by Django 5.2.4 on 2025-08-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer covered by this contract",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="customers.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                help_text="Service/product covered by this contract",
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
