# Generated by Django 5.2.4 on 2025-08-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the %(class)s was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the %(class)s was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Active contract for this customer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="contracts.contract",
                        verbose_name="Contract",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        help_text="Original lead that became a customer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer",
                        to="leads.lead",
                        verbose_name="Lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
            },
        ),
    ]
