# Generated by Django 5.2.4 on 2025-09-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contract",
            field=models.OneToOneField(
                help_text="Active contract for this customer",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer",
                to="contracts.contract",
                verbose_name="Contract",
            ),
        ),
    ]
