# Generated by Django 5.2.4 on 2025-08-06 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the %(class)s was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the %(class)s was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the advertising campaign",
                        max_length=255,
                        verbose_name="Campaign name",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("social", "Social Media"),
                            ("search", "Search Engines"),
                            ("context", "Context Ads"),
                            ("email", "Email Marketing"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="social",
                        help_text="Primary advertising channel",
                        max_length=20,
                        verbose_name="Advertising channel",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget for the campaign",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Budget",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is campaign currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being advertised",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ["-cost"],
            },
        ),
    ]
