# Generated by Django 5.2.4 on 2025-09-04 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="channel",
            field=models.CharField(
                choices=[
                    ("social", "Social Media"),
                    ("search", "Search Engines"),
                    ("context", "Context Ads"),
                    ("email", "Email Marketing"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="social",
                max_length=20,
                verbose_name="Advertising channel",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Budget",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Campaign name"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
