from typing import Any
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db.models import Sum

from contracts.models import Contract
from crm.models import BaseModel
from crm.cache import cache_method  # Импортируем декоратор


class Advertisement(BaseModel):
    """Represents an advertising campaign with caching"""

    class Meta:
        ordering = ["-cost"]
        verbose_name = _("Advertisement")
        verbose_name_plural = _("Advertisements")

    class Channel(models.TextChoices):
        SOCIAL = "social", _("Social Media")
        SEARCH = "search", _("Search Engines")
        CONTEXT = "context", _("Context Ads")
        EMAIL = "email", _("Email Marketing")
        OTHER = "other", _("Other")

    name = models.CharField(
        max_length=255,
        db_index=True,
        verbose_name=_("Campaign name"),
    )
    channel = models.CharField(
        max_length=20,
        db_index=True,
        choices=Channel.choices,
        default=Channel.SOCIAL,
        verbose_name=_("Advertising channel"),
    )
    cost = models.DecimalField(
        validators=[MinValueValidator(0)],
        max_digits=12,
        decimal_places=2,
        verbose_name=_("Budget"),
    )
    product = models.ForeignKey(
        "products.Product",
        on_delete=models.CASCADE,
        verbose_name=_("Product"),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Active"),
    )
    leads: models.Manager

    @cache_method(timeout=600)
    def leads_count(self) -> Any:
        """Returns the number of leads generated by this campaign"""
        print(f"📊 [LEADS COUNT] Вычисляю для advertisement_{self.pk}")
        return self.leads.count()

    @cache_method(timeout=600)
    def customers_count(self) -> Any:
        """Returns number of leads converted to customers"""
        print(f"📊 [CUSTOMERS COUNT] Вычисляю для advertisement_{self.pk}")
        return self.leads.filter(customer__isnull=False).count()

    @cache_method(timeout=600)
    def conversion_rate(self) -> Any:
        """Calculates lead to customer conversion rate"""
        print(f"📊 [CONVERSION RATE] Вычисляю для advertisement_{self.pk}")
        total_leads = self.leads_count()
        if total_leads == 0:
            return 0.0
        return round(self.customers_count() / total_leads, 2)

    @cache_method(timeout=600)
    def profit(self) -> float | None:
        """Calculates ROI (return on investment) ratio"""
        print(f"📊 [PROFIT] Вычисляю ROI для advertisement_{self.pk}")
        if not self.cost:
            return None

        total_income = (
            Contract.objects.filter(customer__lead__advertisement=self).aggregate(
                total_income=Sum("cost")
            )["total_income"]
            or 0
        )

        if total_income:
            roi = float(total_income) / float(self.cost)
            return round(roi, 2)

        return None

    def get_absolute_url(self) -> Any:
        return reverse("advertisements:detail", kwargs={"pk": self.pk})