name: Django CI Pipeline

on:
  push:
    branches: [dev, test-ci]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Debug - Show directory structure
        run: ls -la

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry==1.8.2

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction
          poetry run pip install psycopg2-binary

      - name: Run linters
        run: |
          poetry run black --check .
          poetry run isort --check .
          poetry run flake8 .
          poetry run pylint crm/
          poetry run mypy .

      - name: Run Django tests
        run: |
          poetry run python manage.py test