name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry==1.8.2

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run linters
        run: |
          poetry run black --check .
          poetry run isort --check .
          poetry run flake8 .
          poetry run pylint ваш_пакет/
          poetry run mypy .
